# This file was generated by GoReleaser. DO NOT EDIT.
cask "devproof" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "7cf860f6d38478f76c929e0f6b45b46261bce15f211344f1d783b5540f61c195"
      url "https://github.com/thingzio/devproof/releases/download/v#{version}/devproof_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8cd69daf7a13d6b10874e5d17256a845e3c8ae2ad0b093769a9e8e85adad5a84"
      url "https://github.com/thingzio/devproof/releases/download/v#{version}/devproof_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3c206cb217fb89c7a22a706e883ba15d085f256931e351520a96462de20dacff"
      url "https://github.com/thingzio/devproof/releases/download/v#{version}/devproof_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "56df19758408552f373b3380883fe6ae21691b030f004641f3d35a6c997106e6"
      url "https://github.com/thingzio/devproof/releases/download/v#{version}/devproof_#{version}_linux_amd64.tar.gz"
    end
  end

  name "devproof"
  desc "Build, verify, and expand immutable OCI bundles"
  homepage "https://github.com/thingzio/devproof"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devproof"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/devproof"]
    end
  end

  # No zap stanza required
end
