# This file was generated by GoReleaser. DO NOT EDIT.
cask "devproof" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/devproof"]
    end
  end

  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "ccdf375c6f59285e8edd871cf4a861f5fa3f07d9d189acec554c33d51c5dddf2"
      url "https://github.com/thingzio/devproof/releases/download/v#{version}/devproof_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f44321baf9849dbf4aa00a5816866f2e5469a46cb6b6deb6f68296f99bed30da"
      url "https://github.com/thingzio/devproof/releases/download/v#{version}/devproof_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4884c69ded450de7c2b3a1fca50c53c9706a7c2ae972afaf6ec2329f470e9b83"
      url "https://github.com/thingzio/devproof/releases/download/v#{version}/devproof_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0a1794ce626831f3ccd80ca417fcc9baf0e812b028ba7eef3bcd15a6910f7a64"
      url "https://github.com/thingzio/devproof/releases/download/v#{version}/devproof_#{version}_linux_amd64.tar.gz"
    end
  end

  name "devproof"
  desc "Build, verify, and expand immutable OCI bundles"
  homepage "https://github.com/thingzio/devproof"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devproof"

  # No zap stanza required
end
