# This file was generated by GoReleaser. DO NOT EDIT.
cask "devproof" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/devproof"]
    end
  end

  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "73f0f0a8c66ccaef072abca3e000e6db4427d28bbe8fa8c24e602002655b45ff"
      url "https://github.com/thingzio/devproof/releases/download/v#{version}/devproof_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "07fadf9095a251cb4fce57ae395cdf43ebd192591d36f8aa48e0e75b16763f6d"
      url "https://github.com/thingzio/devproof/releases/download/v#{version}/devproof_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2f3191efec7984445628e515b61913295f00cf6bbcbb283a6ef2aae21e56b211"
      url "https://github.com/thingzio/devproof/releases/download/v#{version}/devproof_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "aaf9e99a7f9a932be502279b39f28b3d04a616469af18d90dba1a2c69bf191fb"
      url "https://github.com/thingzio/devproof/releases/download/v#{version}/devproof_#{version}_linux_amd64.tar.gz"
    end
  end

  name "devproof"
  desc "Build, verify, and expand immutable OCI bundles"
  homepage "https://github.com/thingzio/devproof"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devproof"

  # No zap stanza required
end
