# This file was generated by GoReleaser. DO NOT EDIT.
cask "devradarctl" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "0dc76210f4f3feffd356d1062beffe9c602e9330a6e9b5a72b1d0e5a9d88d27a"
      url "https://github.com/thingzio/devradarctl/releases/download/v#{version}/devradarctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "779ad5d808646867be60b0aba4837bce0fbd7958dd075154049928b0beca0dc4"
      url "https://github.com/thingzio/devradarctl/releases/download/v#{version}/devradarctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "56b638646bc6b1f0c35764e5237c5460d4f1a9b15cbbae50d7c59ab15db93323"
      url "https://github.com/thingzio/devradarctl/releases/download/v#{version}/devradarctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a2d20e4e12cf3d101bbb079afca345a98a46550aa92b314199f88103c35e796a"
      url "https://github.com/thingzio/devradarctl/releases/download/v#{version}/devradarctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "devradarctl"
  desc "CLI to generate and submit SBOMs to DevRadar"
  homepage "https://github.com/thingzio/devradarctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devradarctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/devradarctl"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    devradarctl generates SBOMs with syft, which is not bundled.
    Install it separately: brew install syft
  EOS
end
