# This file was generated by GoReleaser. DO NOT EDIT.
cask "devradarctl" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "1b9a95e9772207d4c373f2205ad81b093c89fcee93e3a897e4f1cd3d982bad22"
      url "https://github.com/thingzio/devradarctl/releases/download/v#{version}/devradarctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0d8881d6b5426dd99ef1fcded2bad838f84d07c3dab75a72c832b2db28f38aa8"
      url "https://github.com/thingzio/devradarctl/releases/download/v#{version}/devradarctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2bfe90a167438e9fbae6729b6bc39d7b5e1e12c42e00b097b9b9af6515ef129c"
      url "https://github.com/thingzio/devradarctl/releases/download/v#{version}/devradarctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "571277699ad4ffd4b881f229c681cb6dfd81377a2313325ead6ee9ed7aca8a5a"
      url "https://github.com/thingzio/devradarctl/releases/download/v#{version}/devradarctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "devradarctl"
  desc "CLI to generate and submit SBOMs to DevRadar"
  homepage "https://github.com/thingzio/devradarctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devradarctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/devradarctl"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    devradarctl generates SBOMs with syft, which is not bundled.
    Install it separately: brew install syft
  EOS
end
