# This file was generated by GoReleaser. DO NOT EDIT.
cask "devradarctl" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "4650ac3fc2696b77569e4013e42dff01211f962531ea8883c2256d6d4cd04ba3"
      url "https://github.com/thingzio/devradarctl/releases/download/v#{version}/devradarctl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "94861c5726ae23469ad0beddfb62177b2b44b7298a2349ab2800f0e762ae7561"
      url "https://github.com/thingzio/devradarctl/releases/download/v#{version}/devradarctl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ffc03a85cffe6eef7728196177c39d4886e7d823e84e97d7bb0874deb4459d4e"
      url "https://github.com/thingzio/devradarctl/releases/download/v#{version}/devradarctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4178feef409b9c72aa208df84eb365451422fb24a7b4927c061d0b77f3ed7888"
      url "https://github.com/thingzio/devradarctl/releases/download/v#{version}/devradarctl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "devradarctl"
  desc "CLI to generate and submit SBOMs to DevRadar"
  homepage "https://github.com/thingzio/devradarctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devradarctl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/devradarctl"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    devradarctl generates SBOMs with syft, which is not bundled.
    Install it separately: brew install syft
  EOS
end
